name: CI

on: [push, pull_request]

jobs:
  Lint addon docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: lint
      run: NODE=$(which node) make lint-addon-docs
      
  Lint C++ files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: make lint-cpp

  Lint docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: lint
      run: NODE=$(which node) make lint-md

  Lint JavaScript files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: lint
      run: NODE=$(which node) make lint-js
