name: CI

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: NODE=$(which node) make doc-only
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: out/doc
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./configure && make -j2
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - name: Install deps
        run: choco install nasm
      - name: Build
        run: ./vcbuild.bat
  build-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./configure && make -j8
  lint-addon-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint addon docs
      run: NODE=$(which node) make lint-addon-docs
  lint-commit-message:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lints message of the first commit in this pull request
        continue-on-error: true
        run: bash -x tools/lint-pr-commit-message.sh ${{ github.event.number }} || echo ::set-env name=needs_fixup::true
      - name: Label on commit message lint failure
        if: env.needs_fixup == 'true'
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label "needs commit message fix"
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint C/C++ files
      run: make lint-cpp
  lint-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint docs
      run: NODE=$(which node) make lint-md
  lint-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Lint JavaScript files
      run: NODE=$(which node) make lint-js
